### ISSUE TITLE
Push verification ends with "TypeError: can only concatenate str (not "NoneType") to str"

### ISSUE THREAD

**Issue by wonderg** [jmhale/okta-awscli#109]
**Describe the bug**
Not able to login using Okta Verify. Checked both kinds regular and Push and result are the same - TypeError: can only concatenate str (not "NoneType") to str

**To Reproduce**
1. Configure ~/.okta-aws 
2. Run CLI tool with specific okta and aws profiles 
okta-awscli --okta-profile okta-aws206 --profile okta-aws206 --debug
3. Catch the error 

**Expected behavior**
 ~/.aws/credentials should be updated with a token for okta-aws206

**Output**
Output of your okta-awscli run, using the `--debug` flag.
```
okta-awscli --okta-profile okta-aws206 --profile okta-aws206 --debug
INFO - Temporary credentials have expired. Requesting new credentials.
INFO - Authenticating to: somecompany.okta.com
INFO - Authenticating as: name.surname
Enter password: 
INFO - App Link set as: https://somecompany.okta.com/home/amazon_aws/0oa1f32y7xf1K56aT1d8/272  # Found in Okta's configuration for your AWS account.
ERROR - Unsupported factorType: sms
Registered MFA factors:
1: Google Authenticator
2: Okta Verify - Push
3: Okta Verify
Please select the MFA factor: 2
INFO - Performing secondary authentication using: OKTA
DEBUG - {'id': 'opf1drfq8icq0OkZ21d8', 'factorType': 'push', 'provider': 'OKTA', 'vendorName': 'OKTA', 'profile': {'credentialId': 'name.surname@somecompany.okta.com', 'deviceType': 'SmartPhone_IPhone', 'keys': [{'kty': 'PKIX', 'use': 'sig', 'kid': 'default', 'x5c': ['MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsua0l7mgnN1NmZ8aS9gNLhEeEPpft40umIouk+TjyugDFKMFXD8L5vYcstLxKjzMkm/E+0o0HUeF3zRpKci+QlYGv6rhZ7udwTRKHyCoIQ9gpF3T95qM5NRLjscg1rFSURfmjXMPTmDOTDOXcTBlNvfSqU0DZSSf9MTF2kvL9MI37HkNRU307x26tSzNMTykqhQ1/gNd0AYaQ9es7yJhE5HYaUBqY1oRMJh3Xhm1C068NKgcc58mHXwXSF91Z9l9+ZvgHGboMEajZMIp5FmmajzS9BJb9A6PaBb4W6M96q1yU9RNHQcG4uYjBAY1vAnVXJjNs1Ygd4pBvCr0951HHwIDAQAB']}], 'name': 'GS.phone', 'platform': 'IOS', 'version': '11.2.6'}, '_links': {'verify': {'href': 'https://somecompany.okta.com/home/amazon_aws/0oa1f32y7xf1K56aT1d8/verify', 'hints': {'allow': ['POST']}}}}
Waiting for push verification...
ERROR - No Extra Verification
Traceback (most recent call last):
  File "/usr/local/bin/okta-awscli", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/oktaawscli/okta_awscli.py", line 113, in main
    aws_auth, okta_profile, profile, verbose, logger, token, cache
  File "/usr/local/lib/python3.7/site-packages/oktaawscli/okta_awscli.py", line 19, in get_credentials
    _, assertion = okta.get_assertion()
  File "/usr/local/lib/python3.7/site-packages/oktaawscli/okta_auth.py", line 363, in get_assertion
    assertion = self.get_saml_assertion(resp)
  File "/usr/local/lib/python3.7/site-packages/oktaawscli/okta_auth.py", line 285, in get_saml_assertion
    self.logger.error("SAML assertion not valid: " + assertion)
TypeError: can only concatenate str (not "NoneType") to str
```

**Environment (please complete the following information):**
 - OS: MacOS 10.14.4
 - Version of okta-awscli 0.4.0

**Additional context**
~/.okta-aws
```
➜ cat ~/.okta-aws     looks like this                                           
[okta-aws206]
base-url = somecompany.okta.com

username =name.surname
app-link = https://somecompany.okta.com/home/amazon_aws/0oa1f32y7xf1K56aT1d8/272  
```

**Comment by dovy** [comment]
Same

**Comment by rohanprasad** [comment]
I RCA'd this to an error on Okta's end. In my case I didn't have access to the app in okta. @jmhale I was thinking to raise a PR to show this error message instead on crashing, let me know.

**Comment by jmhale** [comment]
@rohanprasad That makes sense. You're probably getting the Extra Verification page in Okta, which is pushing down the per-app MFA logic branch in `okta-awscli`, but then it's freaking out when it doesn't get an assertion back. 

I think we just need to clean up how that logging statement looks and handles a NoneType `assertion`.

A PR is more than welcome if you have one handy. Note that I just refactored a bunch of other stuff related to MFA, so you might need to pull a fresh `develop` branch down.

**Comment by kvsouza** [comment]
Same. Any solution?

**Comment by duncz** [comment]
I'm encountering the same problem. If I add some `print`s to the `okta-awscli` module, it looks like the `get_simple_assertion` / `get_mfa_assertion` from `okta_auth.py` are returning a basic HTML containing a JavaScript redirect which BeautifulSoup can't handle.

Is this something to do with an Okta change? Or perhaps I'm using `okta-awscli` incorrectly? I noticed on an Okta blog video for instance that they ran `aws configure sso` - is this something I need to do before using `okta-awscli`?

**Comment by angelalbericisfdc** [comment]
Team, do we have any workaround? it's a showstopper for one of my team members; we are unsure of what is producing it 
FYI @jmhale

**Comment by ido-vcita** [comment]
Any updates? We are having issues as well with okta and AWS SSO :(

**Comment by banyek** [comment]
crickets...

**Comment by maxtacu** [comment]
> help
will try on weekend to take a look

**Comment by kedare** [comment]
I just gave up and used this one that works perfectly 
https://github.com/okta/okta-aws-cli

**Comment by vinod4086** [comment]
Hi All..  I faced this issue at times..  And the resolution is, I had to turn-off my cyber-security tool zscaler in-order to authenticate with okta-awscli..
Once after the authentication, I will enable zscaler..  Hope this helps for some users..

**Comment by be-a-bee** [comment]
Hi All, I am also facing this issue. 

user@L100687MIN ~ % okta-awscli --okta-profile uas --profile uas
Enter password: 
ERROR - Unsupported factorType: sms
Registered MFA factors:
1: Okta Verify - Push
2: Okta Verify
Please select the MFA factor: 2
Enter MFA verification code: 123456
ERROR - No Extra Verification
Traceback (most recent call last):
  File "/opt/homebrew/bin/okta-awscli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/opt/python-click/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/python-click/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/python-click/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/python-click/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/okta-awscli/0.5.4_3/libexec/lib/python3.12/site-packages/oktaawscli/okta_awscli.py", line 141, in main
    get_credentials(
  File "/opt/homebrew/Cellar/okta-awscli/0.5.4_3/libexec/lib/python3.12/site-packages/oktaawscli/okta_awscli.py", line 36, in get_credentials
    _, assertion = okta.get_assertion()
                   ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/okta-awscli/0.5.4_3/libexec/lib/python3.12/site-packages/oktaawscli/okta_auth.py", line 165, in get_assertion
    assertion = self.get_saml_assertion(resp)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/okta-awscli/0.5.4_3/libexec/lib/python3.12/site-packages/oktaawscli/okta_auth.py", line 149, in get_saml_assertion
    self.logger.error("SAML assertion not valid: " + assertion)
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
