### ISSUE TITLE
TypeError: expected string or bytes-like `object`

### ISSUE THREAD

**Issue by JordanWake** [jmhale/okta-awscli#142]
**Describe the bug**
When running okta-awscli I get an error after entering the password field (no matter what is entered for URL and username)

**To Reproduce**
pip install okta-awscli
okta-awscli
Enter anything for password field

**Expected behavior**
For password field to pass

**Output**
```
okta-awscli --debug
Enter username: test
Enter password: 
Traceback (most recent call last):
  File "/Users/jwake/Library/Python/3.8/bin/okta-awscli", line 8, in <module>
    sys.exit(main())
  File "/Users/jwake/Library/Python/3.8/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jwake/Library/Python/3.8/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jwake/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jwake/Library/Python/3.8/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jwake/Library/Python/3.8/lib/python/site-packages/oktaawscli/okta_awscli.py", line 114, in main
    get_credentials(
  File "/Users/jwake/Library/Python/3.8/lib/python/site-packages/oktaawscli/okta_awscli.py", line 18, in get_credentials
    okta = OktaAuth(okta_profile, verbose, logger, totp_token, okta_auth_config)
  File "/Users/jwake/Library/Python/3.8/lib/python/site-packages/oktaawscli/okta_auth.py", line 25, in __init__
    self.app_link = okta_auth_config.app_link_for(okta_profile)
  File "/Users/jwake/Library/Python/3.8/lib/python/site-packages/oktaawscli/okta_auth_config.py", line 45, in app_link_for
    if not validators.url(app_link):
  File "<decorator-gen-29>", line 2, in url
  File "/Users/jwake/Library/Python/3.8/lib/python/site-packages/validators/utils.py", line 83, in wrapper
    value = func(*args, **kwargs)
  File "/Users/jwake/Library/Python/3.8/lib/python/site-packages/validators/url.py", line 148, in url
    result = pattern.match(value)
TypeError: expected string or bytes-like `object`
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Version of okta-awscli you're running. 0.4.4
- Python 3.8.2
- Also tried on 3.9.0 and 3.6.5 and in pyenv virtual environment and outside of pyenv virtual environment

**Additional context**

**Comment by JordanWake** [comment]
So after configuring it again, the issue seemed to have solved itself. I am not sure what I did wrong in the configuration file the first time.
