### ISSUE TITLE
AWS Region set in .aws/config can override STS call

### ISSUE THREAD

**Issue by jmhale** [jmhale/okta-awscli#19]
When a region is set in `~/.aws/config`, the STS call using boto will use that region, instead of a default of `us-east-1`.

Most of the time, this isn't problematic, since the region set there is valid. However, if the region is set to an invalid value, okta-awscli will fail.

For example, this `~/.aws/config` will cause issues:

```
[default]
region = None
```

Resulting in this trace:
```
Traceback (most recent call last):
  File "/usr/local/bin/okta-awscli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oktaawscli/okta_awscli.py", line 55, in main
    get_credentials(aws_auth, okta_profile, profile, verbose)
  File "/usr/local/lib/python2.7/dist-packages/oktaawscli/okta_awscli.py", line 16, in get_credentials
    token = aws_auth.get_sts_token(role_arn, principal_arn, assertion)
  File "/usr/local/lib/python2.7/dist-packages/oktaawscli/aws_auth.py", line 51, in get_sts_token
    SAMLAssertion=assertion)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 602, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://sts.None.amazonaws.com/"
```

I'm not sure why this region is getting set to None. The user that reported this says that it was set to `None` upon installing `awscli` and with no further configuration, although I have not independently confirmed. 

Either way, the region in the STS calls should be set explicitly or set to ignore invalid values, such as `None`

**Comment by jmhale** [comment]
Going to "never" this instead. Since this is a `botocore` error and we're not modifying `config` it at all, we shouldn't be mucking with it here.

If `awscli` is setting the region to `None` on initial config, then that should be opened as a bug in that project instead. `awscli` won't work with the region being set that way, regardless whether or not this project is used.
