### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by cbitterfield** [jmhale/okta-awscli#44]
When attempting to use the CLI in Python 3.6 this error message occurs.

1. OSX (10.13.6), Python 3.6.6, pip-3.6
2. AWS CLI = awscli-1.15.68
      aws-cli/1.15.68 Python/3.6.6 Darwin/17.7.0 botocore/1.10.67

~ cbitterfield$ okta-awscli 
Registered MFA factors:
1: Okta Verify - Push
2: Okta Verify
Please select the MFA factor: 1
Traceback (most recent call last):
  File "/Users/cbitterfield/Library/Python/3.6/bin/okta-awscli", line 11, in <module>
    load_entry_point('okta-awscli==0.2.3', 'console_scripts', 'okta-awscli')()
  File "/Users/cbitterfield/Library/Python/3.6/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cbitterfield/Library/Python/3.6/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/cbitterfield/Library/Python/3.6/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cbitterfield/Library/Python/3.6/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/cbitterfield/Library/Python/3.6/lib/python/site-packages/oktaawscli/okta_awscli.py", line 104, in main
    aws_auth, okta_profile, profile, verbose, logger, token, cache
  File "/Users/cbitterfield/Library/Python/3.6/lib/python/site-packages/oktaawscli/okta_awscli.py", line 19, in get_credentials
    _, assertion = okta.get_assertion()
  File "/Users/cbitterfield/Library/Python/3.6/lib/python/site-packages/oktaawscli/okta_auth.py", line 199, in get_assertion
    session_token = self.primary_auth()
  File "/Users/cbitterfield/Library/Python/3.6/lib/python/site-packages/oktaawscli/okta_auth.py", line 40, in primary_auth
    session_token = self.verify_mfa(factors_list, state_token)
  File "/Users/cbitterfield/Library/Python/3.6/lib/python/site-packages/oktaawscli/okta_auth.py", line 97, in verify_mfa
    factor_choice = input('Please select the MFA factor: ') - 1
TypeError: unsupported operand type(s) for -: 'str' and 'int'

**Comment by jstinson** [comment]
I'm seeing the same issue with python 2.7:

`usrad-extaxc:~ adj$ okta-awscli --profile qscb_dev
Enter username:
Enter password: 
Registered MFA factors:
1: Okta Verify - Push
2: Okta Verify
Please select the MFA factor: 1
Traceback (most recent call last):
  File "/Users/adj/Library/Python/2.7/bin/okta-awscli", line 9, in <module>
    load_entry_point('okta-awscli==0.2.3', 'console_scripts', 'okta-awscli')()
  File "/Users/adj/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adj/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/adj/Library/Python/2.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adj/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/adj/Library/Python/2.7/lib/python/site-packages/oktaawscli/okta_awscli.py", line 104, in main
    aws_auth, okta_profile, profile, verbose, logger, token, cache
  File "/Users/adj/Library/Python/2.7/lib/python/site-packages/oktaawscli/okta_awscli.py", line 19, in get_credentials
    _, assertion = okta.get_assertion()
  File "/Users/adj/Library/Python/2.7/lib/python/site-packages/oktaawscli/okta_auth.py", line 199, in get_assertion
    session_token = self.primary_auth()
  File "/Users/adj/Library/Python/2.7/lib/python/site-packages/oktaawscli/okta_auth.py", line 40, in primary_auth
    session_token = self.verify_mfa(factors_list, state_token)
  File "/Users/adj/Library/Python/2.7/lib/python/site-packages/oktaawscli/okta_auth.py", line 97, in verify_mfa
    factor_choice = input('Please select the MFA factor: ') - 1
TypeError: unsupported operand type(s) for -: 'str' and 'int'`

**Comment by jstinson** [comment]
Update: I was able to get push to work by adding this line to ~/.okta-aws:

factor = OKTA

**Comment by jmhale** [comment]
Fixed in #48 (and released in #51). Closing.
