### ISSUE TITLE
What Python version ?

### ISSUE THREAD

**Issue by tkang007** [jmhale/okta-awscli#55]
Hi,

Thanks for your valuable project.  What Python version should I use?  

I have problem with Python 3.6 at CentOs 7 as below. 

Could you help me to resolve below error?  

.okta-aws file:

[default]
base-url = xxx.okta.com/home/amazon_aws/0oaxxxxfw1bRFjTaDM0x7/NNN  
username = xxx
password = yyy  
role = zzz

command:
okta-awscli  --profile dev  iam users

error:
[root@centos75a ~]# okta-awscli iam list-user
Traceback (most recent call last):
  File "/usr/local/bin/okta-awscli", line 11, in <module>
    load_entry_point('okta-awscli==0.2.4', 'console_scripts', 'okta-awscli')()
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oktaawscli/okta_awscli.py", line 104, in main
    aws_auth, okta_profile, profile, verbose, logger, token, cache
  File "/usr/local/lib/python3.6/site-packages/oktaawscli/okta_awscli.py", line 19, in get_credentials
    _, assertion = okta.get_assertion()
  File "/usr/local/lib/python3.6/site-packages/oktaawscli/okta_auth.py", line 199, in get_assertion
    session_token = self.primary_auth()
  File "/usr/local/lib/python3.6/site-packages/oktaawscli/okta_auth.py", line 35, in primary_auth
    resp_json = resp.json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tkang007** [comment]
I found okta-awscli3
