### ISSUE TITLE
Better handling of missing default profile

### ISSUE THREAD

**Issue by jmhale** [jmhale/okta-awscli#57]
**Describe the bug**
When no `[default]` profile is included in `~/.okta-aws`, okta-awscli outputs a ugly trace.

**To Reproduce**
1. Create a `~/.okta-aws` file with no `[default]` profile.
2. Run `okta-awscli` without specifying a named profile via `--okta-profile`.

**Expected behavior**
okta-awscli should output a clean message, telling the user to either define a default profile or specify a named profile in the command line argument.

**Output**
```
okta-awscli --debug                                                                                                        ✘  09:11:32  okta
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jhale/.virtualenvs/okta/bin/okta-awscli", line 11, in <module>
    sys.exit(main())
  File "/Users/jhale/.virtualenvs/okta/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jhale/.virtualenvs/okta/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/jhale/.virtualenvs/okta/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jhale/.virtualenvs/okta/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/jhale/.virtualenvs/okta/lib/python3.6/site-packages/oktaawscli/okta_awscli.py", line 104, in main
    aws_auth, okta_profile, profile, verbose, logger, token, cache
  File "/Users/jhale/.virtualenvs/okta/lib/python3.6/site-packages/oktaawscli/okta_awscli.py", line 17, in get_credentials
    okta = OktaAuth(okta_profile, verbose, logger, totp_token, okta_auth_config)
  File "/Users/jhale/.virtualenvs/okta/lib/python3.6/site-packages/oktaawscli/okta_auth.py", line 25, in __init__
    self.https_base_url = "https://%s" % okta_auth_config.base_url_for(okta_profile)
  File "/Users/jhale/.virtualenvs/okta/lib/python3.6/site-packages/oktaawscli/okta_auth_config.py", line 30, in base_url_for
    base_url = self._value.get('default', 'base-url')
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'default'
```

**Environment (please complete the following information):**
 - OS: MacOS 10.14
 - Version of okta-awscli you're running. `okta-awscli -V`: `0.2.5`

**Comment by jmhale** [comment]
Fixed in #118
